blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/programmingHLS/repo-standardizer/discussions
    about: Ask questions and share ideas here
  - name: Security
    url: https://github.com/programmingHLS/repo-standardizer/security/policy
    about: Please report security vulnerabilities here
